kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "go-echo42665f8d-c075-4718-9eb2-983190526040.labels" . | nindent 4 }}
    openservicemesh.io/monitored-by: osm
  annotations:
    openservicemesh.io/sidecar-injection: enabled

