kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "go-echo55d59f67-eb5d-4e5c-81fb-136c5e52e39a.labels" . | nindent 4 }}
    openservicemesh.io/monitored-by: osm
    kubernetes.azure.com/generator: devhub
  annotations:
    openservicemesh.io/sidecar-injection: enabled

