kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "go-echo200cf607-aa63-41d8-b42c-dae582d8c460.labels" . | nindent 4 }}
    openservicemesh.io/monitored-by: osm
    kubernetes.azure.com/generator: devhub
  annotations:
    openservicemesh.io/sidecar-injection: enabled

