kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "go-echo0145d19d-1f6f-4040-ae52-4cb3b6d58051.labels" . | nindent 4 }}
    openservicemesh.io/monitored-by: osm
  annotations:
    openservicemesh.io/sidecar-injection: enabled

