kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "go-echo78d1a4ac-1963-468e-8cce-360f109fb2b5.labels" . | nindent 4 }}
    openservicemesh.io/monitored-by: osm
    kubernetes.azure.com/generator: devhub
  annotations:
    openservicemesh.io/sidecar-injection: enabled

