kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "go-echo4d068cee-ffe6-4335-a650-883833ec0e41.labels" . | nindent 4 }}
    openservicemesh.io/monitored-by: osm
  annotations:
    openservicemesh.io/sidecar-injection: enabled

